version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: "__LOG_FILE__"
    encoding: utf-8

root:
  level: INFO
  handlers: [console, file]

loggers:
  watchfiles.main:
    level: WARNING
    handlers: [file, console]
    propagate: false
  uvicorn:
    level: INFO
    propagate: true
  uvicorn.error:
    level: INFO
    propagate: true
  uvicorn.access:
    level: INFO
    propagate: true
