\
.PHONY: clear install migrate dev dev-nolog run update-db update-env clean

ENV_FILE := environment.yml
ENV_PATH := .conda/env
HOST := 127.0.0.1
PORT := 8000

CONDA := conda
RUN := $(CONDA) run -p $(ENV_PATH)

clear:
	@python -c "print('\033c', end='')"

# --- Migrate DB to latest revision ---
migrate:
	$(RUN) alembic upgrade head

# --- Install/update local conda env and run migrations ---
install: clear
	@echo make install
	@python -c "import os,sys,subprocess; \
env_path=r'$(ENV_PATH)'; yml=r'$(ENV_FILE)'; \
py_win=os.path.join(env_path,'python.exe'); py_nix=os.path.join(env_path,'bin','python'); \
exists=os.path.isdir(env_path) and (os.path.isfile(py_win) or os.path.isfile(py_nix)); \
cmd=(['conda','env','create','-p',env_path,'-f',yml] if not exists else ['conda','env','update','-p',env_path,'-f',yml,'--prune']); \
print('Running:', ' '.join(cmd)); \
sys.exit(subprocess.call(cmd))"
	$(MAKE) migrate

# --- Dev server (reload) WITH logging ---
# Writes: ./.log/<YYYY_MM_DD_HH_MM_SS>-<PID>.log
# Uses logging.yaml with "__LOG_FILE__" placeholder, generates .log/logging.runtime.yaml
dev: install
	$(CONDA) run -p $(ENV_PATH) python -c "import datetime, pathlib, os; \
pathlib.Path('.log').mkdir(parents=True, exist_ok=True); \
ts=datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S'); \
pid=str(os.getpid()); \
log_file=(pathlib.Path('.log')/f'{ts}-{pid}.log').resolve().as_posix(); \
base=pathlib.Path('logging.yaml').read_text(encoding='utf-8'); \
runtime=base.replace('__LOG_FILE__', log_file); \
(pathlib.Path('.log')/'logging.runtime.yaml').write_text(runtime, encoding='utf-8'); \
os.execvp('uvicorn',[ \
'uvicorn','app.main:app', \
'--reload', \
'--reload-dir','app', \
'--host','$(HOST)', \
'--port','$(PORT)', \
'--log-config', str((pathlib.Path('.log')/'logging.runtime.yaml').resolve()) \
])"

# --- Dev server (reload) WITHOUT custom log config ---
dev-nolog: install
	$(RUN) uvicorn app.main:app --reload --reload-dir app --host $(HOST) --port $(PORT)

# --- Run server (no reload) WITH logging ---
run: install
	$(CONDA) run -p $(ENV_PATH) python -c "import datetime, pathlib, os; \
pathlib.Path('.log').mkdir(parents=True, exist_ok=True); \
ts=datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S'); \
pid=str(os.getpid()); \
log_file=(pathlib.Path('.log')/f'{ts}-{pid}.log').resolve().as_posix(); \
base=pathlib.Path('logging.yaml').read_text(encoding='utf-8'); \
runtime=base.replace('__LOG_FILE__', log_file); \
(pathlib.Path('.log')/'logging.runtime.yaml').write_text(runtime, encoding='utf-8'); \
os.execvp('uvicorn',[ \
'uvicorn','app.main:app', \
'--host','$(HOST)', \
'--port','$(PORT)', \
'--log-config', str((pathlib.Path('.log')/'logging.runtime.yaml').resolve()) \
])"

# --- Create an autogenerated migration and apply it ---
update-db: install
	@python -c "import os; os.makedirs(r'alembic/versions', exist_ok=True)"
	$(RUN) alembic revision --autogenerate -m "auto"
	$(MAKE) migrate

# --- Recreate the local env from scratch (delete .conda then create) ---
update-env: clear
	@echo make update-env
	@python -c "import shutil; shutil.rmtree('.conda', ignore_errors=True)"
	@python -c "import subprocess,sys; \
env_path=r'$(ENV_PATH)'; yml=r'$(ENV_FILE)'; \
cmd=['conda','env','create','-p',env_path,'-f',yml]; \
print('Running:', ' '.join(cmd)); \
sys.exit(subprocess.call(cmd))"
	$(MAKE) migrate

# --- Clean project artifacts (keeps source code) ---
clean: clear
	@echo make clean
	@python -c "import os,shutil; \
p='app.sqlite3'; \
(os.remove(p) if os.path.exists(p) else None); \
shutil.rmtree('.log', ignore_errors=True); \
shutil.rmtree('.conda', ignore_errors=True); \
print('Clean done.')"
