.PHONY: clear install migrate dev dev-nolog run update-db update-env clean

ENV_FILE := environment.yml
ENV_PATH := .conda/env
HOST := 127.0.0.1
PORT := 8000

CONDA := conda
RUN := $(CONDA) run -p $(ENV_PATH)

clear:
	@python -c "print('\033c', end='')"

# --- Migrate DB to latest revision ---
migrate:
	$(RUN) python -c "import subprocess; subprocess.check_call(['alembic','upgrade','head'])"

# --- Install/update local conda env and run migrations ---
# If env missing -> conda env create -p .conda/env -f environment.yml
# Else          -> conda env update -p .conda/env -f environment.yml --prune
install: clear
	@echo make install
	@python -c "import subprocess,os,sys; \
env_path=r'$(ENV_PATH)'; yml=r'$(ENV_FILE)'; \
py_win=os.path.join(env_path,'python.exe'); py_nix=os.path.join(env_path,'bin','python'); \
exists=os.path.isdir(env_path) and (os.path.isfile(py_win) or os.path.isfile(py_nix)); \
cmd=(['conda','env','create','-p',env_path,'-f',yml] if not exists else ['conda','env','update','-p',env_path,'-f',yml,'--prune']); \
print('Running:', ' '.join(cmd)); \
sys.exit(subprocess.call(cmd))"
	$(MAKE) migrate

# --- Dev server (reload) with logging to ./log/<timestamp>.log ---
dev:
	$(RUN) python -c "import os,subprocess,datetime; \
os.makedirs('log', exist_ok=True); \
ts=datetime.datetime.now().strftime('%Y%m%d_%H%M%S'); \
log=f'log/{ts}.log'; \
f=open(log,'w', encoding='utf-8'); \
p=subprocess.Popen(['uvicorn','app.main:app','--reload','--host','$(HOST)','--port','$(PORT)'], stdout=f, stderr=subprocess.STDOUT); \
p.wait()"

# --- Dev server (reload) without log file ---
dev-nolog:
	$(RUN) uvicorn app.main:app --reload --host $(HOST) --port $(PORT)

# --- Run server (no reload). Only installs if env missing. ---
run: clear
	@python -c "import os,subprocess,sys; \
env_path=r'$(ENV_PATH)'; \
py_win=os.path.join(env_path,'python.exe'); py_nix=os.path.join(env_path,'bin','python'); \
exists=os.path.isdir(env_path) and (os.path.isfile(py_win) or os.path.isfile(py_nix)); \
mk=os.environ.get('MAKE','make'); \
sys.exit(subprocess.call([mk,'install']) if not exists else 0)"
	$(RUN) uvicorn app.main:app --host $(HOST) --port $(PORT)

# --- Create an autogenerated migration and apply it ---
# Generates alembic revision with timestamp message and upgrades head.
update-db:
	@python -c "import os; os.makedirs(r'alembic/versions', exist_ok=True)"
	$(RUN) alembic revision --autogenerate -m "auto"
	$(MAKE) migrate

# --- Recreate the local env from scratch (delete .conda then create) ---
# Useful if the env gets corrupted or you want a clean rebuild.
update-env: clear
	@echo make update-env
	@python -c "import shutil; shutil.rmtree('.conda', ignore_errors=True)"
	@python -c "import subprocess,sys; \
env_path=r'$(ENV_PATH)'; yml=r'$(ENV_FILE)'; \
cmd=['conda','env','create','-p',env_path,'-f',yml]; \
print('Running:', ' '.join(cmd)); \
sys.exit(subprocess.call(cmd))"
	$(MAKE) migrate

# --- Clean project artifacts (keeps source code) ---
clean: clear
	@echo make clean
	@python -c "import os,shutil; \
p='app.db'; \
os.remove(p) if os.path.exists(p) else None; \
shutil.rmtree('log', ignore_errors=True); \
shutil.rmtree('.conda', ignore_errors=True); \
print('Clean done.')"
